files:
  - source: /xliff/en.xliff
    translation: /xliff/%two_letters_code%.xliff
files:
  - source: /fastlane/metadata/en-US/description.txt
    translation: /fastlane/metadata/%two_letters_code%/description.txt
files:
  - source: /fastlane/metadata/en-US/keywords.txt
    translation: /fastlane/metadata/%two_letters_code%/keywords.txt
files:
  - source: /fastlane/metadata/en-US/marketing_url.txt
    translation: /fastlane/metadata/%two_letters_code%/marketing_url.txt
files:
  - source: /fastlane/metadata/en-US/name.txt
    translation: /fastlane/metadata/%two_letters_code%/name.txt
files:
  - source: /fastlane/metadata/en-US/privacy_url.txt
    translation: /fastlane/metadata/%two_letters_code%/privacy_url.txt
files:
  - source: /fastlane/metadata/en-US/release_notes.txt
    translation: /fastlane/metadata/%two_letters_code%/release_notes.txt
files:
  - source: /fastlane/metadata/en-US/support_url.txt
    translation: /fastlane/metadata/%two_letters_code%/support_url.txt
